[2018.07.02 23:05:24] (Coverage): Failed to load coverage data from file: C:\Users\Matteo\.IdeaIC2018.1\system\coverage\ing_sw_2018__Velati___Zangrando___Stucchi_$Client.ic
java.io.EOFException
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
	at com.intellij.rt.coverage.util.CoverageIOUtil.readINT(CoverageIOUtil.java:130)
	at com.intellij.rt.coverage.util.ProjectDataLoader.load(ProjectDataLoader.java:38)
	at com.intellij.coverage.IDEACoverageRunner.loadCoverageData(IDEACoverageRunner.java:39)
	at com.intellij.coverage.BaseCoverageSuite.loadProjectInfo(BaseCoverageSuite.java:245)
	at com.intellij.coverage.JavaCoverageSuite.getCoverageData(JavaCoverageSuite.java:177)
	at com.intellij.coverage.CoverageSuitesBundle.getCoverageData(CoverageSuitesBundle.java:95)
	at com.intellij.coverage.SrcFileAnnotator.showCoverageInformation(SrcFileAnnotator.java:289)
	at com.intellij.coverage.CoverageDataManagerImpl$CoverageEditorFactoryListener.lambda$editorCreated$1(CoverageDataManagerImpl.java:707)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
	at com.intellij.util.Alarm$Request.run(Alarm.java:382)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
